package com.unicorn.gameshop.common;

public enum ApiErrorCode {
    BAD_REQUEST,
    ORDER_NOT_FOUND,
    ORDER_EXPIRED,
    PAYMENT_ATTEMPT_NOT_FOUND,
    PAYPAL_ORDER_MISMATCH,
    PAYPAL_AMOUNT_MISMATCH,
    PAYPAL_CAPTURE_NOT_ALLOWED,
    PAYPAL_CAPTURE_FAILED,
    PAYPAL_WEBHOOK_SIGNATURE_INVALID,
    PAYPAL_WEBHOOK_DUPLICATE,
    REFUND_AMOUNT_EXCEEDED,
    REFUND_NOT_ALLOWED,
    FULFILLMENT_NOT_FOUND,
    FULFILLMENT_NOT_ALLOWED,
    FULFILLMENT_RETRYABLE,
    COUNTRY_NOT_SUPPORTED,
    PRODUCT_NOT_AVAILABLE,
    IDEMPOTENCY_CONFLICT,
    ADMIN_ROLE_REQUIRED,
    ADMIN_AUTH_FAILED
}
